# Generated by Django 3.1.3 on 2020-11-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typklienta',
            name='Vat',
        ),
        migrations.AddField(
            model_name='typklienta',
            name='Vat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.vat'),
        ),
    ]
