# Generated by Django 3.1.3 on 2020-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0002_auto_20201122_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typklienta',
            name='Vat',
        ),
        migrations.AddField(
            model_name='typklienta',
            name='Vat',
            field=models.ManyToManyField(null=True, to='TypKlienta.Vat'),
        ),
    ]
