# Generated by Django 3.1.3 on 2020-11-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0003_auto_20201123_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typklienta',
            name='Vat',
        ),
        migrations.AddField(
            model_name='vat',
            name='Vat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.typklienta'),
        ),
    ]
