# Generated by Django 3.1.3 on 2020-11-30 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0004_auto_20201123_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typklienta',
            name='opis',
        ),
        migrations.AlterField(
            model_name='typklienta',
            name='nazwa',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='klient',
            fields=[
                ('IdKlienta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=11)),
                ('metraz', models.IntegerField()),
                ('zuzycie', models.IntegerField()),
                ('typ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.typklienta', to_field='nazwa')),

            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klient',
            },
        ),
    ]
