# Generated by Django 3.1.4 on 2020-12-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TypKlienta', '0005_auto_20201130_2238'),
    ]

    operations = [

        migrations.AddField(
            model_name='klient',
            name='KamId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )

    ]
