# Generated by Django 3.1.3 on 2020-12-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0006_auto_20201203_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WymaganaMocInstalacji',
        ),
    ]
