# Generated by Django 3.1.3 on 2020-12-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0009_klient_wymaganamoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='ekspozycjaDachowa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.ekspozycjadachowa'),
        ),
        migrations.AddField(
            model_name='klient',
            name='kadNachyleniaDachu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.kadnachyleniadachu'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='metraz',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='klient',
            name='zuzycie',
            field=models.IntegerField(),
        ),
    ]
