# Generated by Django 3.1.4 on 2020-12-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0006_auto_20201210_1323'),
        ('TypKlienta', '0015_klient_kamid'),
    ]

    operations = [
    ]
