# Generated by Django 3.1.4 on 2020-12-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0016_merge_20201215_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='LiczbaModulow',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='NazwaModulu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscModulow',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
