# Generated by Django 3.1.4 on 2020-12-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0017_auto_20201215_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='NazwaFalownika',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscFalownika',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
