# Generated by Django 3.1.3 on 2020-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0022_auto_20201218_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='NazwaSystemuMontazowego',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscSystemuMontazowego',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
