# Generated by Django 3.1.3 on 2020-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0023_auto_20201221_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='IloscSkrzynekAC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscSkrzynekAC',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
