# Generated by Django 3.1.3 on 2020-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0024_auto_20201221_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='WartoscOkablowania',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
