# Generated by Django 3.1.3 on 2020-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0025_klient_wartoscokablowania'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='IloscStringow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscStringow',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
