# Generated by Django 3.1.3 on 2020-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0027_auto_20201221_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='KosztTransportu',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
