# Generated by Django 3.1.3 on 2020-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0031_auto_20201222_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='KosztPPOZ',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
