# Generated by Django 3.1.3 on 2021-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0037_klient_kosztinstalacjibrutto'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='MojPrad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='Rabat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='UlgaTermomodernizacyjna',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
