# Generated by Django 3.1.3 on 2021-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0038_auto_20210111_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
