# Generated by Django 3.1.3 on 2020-12-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0008_wymaganamocinstalacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='WymaganaMoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TypKlienta.wymaganamocinstalacji'),
        ),
    ]
