# Generated by Django 3.1.3 on 2020-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0012_auto_20201207_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falowniki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cenanetto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('cenabrutto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Falowniki',
                'verbose_name_plural': 'Falowniki',
            },
        ),
        migrations.CreateModel(
            name='Moduly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('moc', models.DecimalField(decimal_places=3, max_digits=100, null=True)),
                ('cenanetto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('cenabrutto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Moduły fotowoltaiczne',
                'verbose_name_plural': 'Moduły fotowoltaiczne',
            },
        ),
        migrations.CreateModel(
            name='Optymalizatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('cenanetto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('cenabrutto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Optymalizatory',
                'verbose_name_plural': 'Optymalizatory',
            },
        ),
        migrations.CreateModel(
            name='Systemumontazowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cenanetto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('cenabrutto', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Optymalizatory',
                'verbose_name_plural': 'Optymalizatory',
            },
        ),
    ]
