# Generated by Django 3.1.4 on 2020-12-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0021_auto_20201218_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Systemumontazowe',
            new_name='Systemmontazowy',
        ),
    ]
