# Generated by Django 3.1.3 on 2020-12-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0026_auto_20201221_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klient',
            old_name='WartoscOkablowania',
            new_name='WartoscOkablowaniaAC',
        ),
        migrations.AddField(
            model_name='klient',
            name='WartoscOkablowaniaDC',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
