# Generated by Django 3.1.3 on 2020-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0028_klient_koszttransportu'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='KosztMontazu',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
