# Generated by Django 3.1.3 on 2020-12-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0029_klient_kosztmontazu'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='IloscPracGruntowych',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='KosztPracGruntowych',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
