# Generated by Django 3.1.3 on 2020-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0032_klient_kosztppoz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarzaFirmy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marza', models.CharField(max_length=100)),
                ('WartoscMarzy', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
            options={
                'verbose_name': 'Marża firmy',
                'verbose_name_plural': 'Marża firmy',
            },
        ),
    ]
