# Generated by Django 3.1.3 on 2020-12-22 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TypKlienta', '0033_marzafirmy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarzaHandlowca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marza', models.CharField(max_length=100)),
                ('WartoscMarzy', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
                ('KamId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marża handlowca',
                'verbose_name_plural': 'Marża handlowca',
            },
        ),
    ]
