# Generated by Django 3.1.3 on 2021-01-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TypKlienta', '0036_klient_kosztinstalacjinetto'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='KosztInstalacjiBrutto',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
